name: toucan_conda_venv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.9.30
  - cairo=1.16.0
  - certifi=2021.10.8
  - cudatoolkit=11.3.1
  - expat=2.4.4
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gettext=0.19.8.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.14
  - graphviz=2.42.3
  - harfbuzz=2.4.0
  - icu=58.2
  - intel-openmp=2022.0.1
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libuv=1.42.0
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.2.0
  - ncurses=6.2
  - nettle=3.6
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pango=1.42.4
  - pcre=8.45
  - pip=21.0.1
  - pixman=0.40.0
  - python=3.8.11
  - python_abi=3.8
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - readline=8.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - wheel=0.37.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - argparse==1.4.0
    - attrs==21.2.0
    - audioread==2.1.9
    - auraloss==0.2.1
    - cffi==1.14.6
    - charset-normalizer==2.0.4
    - clean-text==0.5.0
    - clldutils==3.9.0
    - colorama==0.4.4
    - colorlog==6.4.1
    - commonmark==0.9.1
    - csvw==1.11.0
    - cycler==0.10.0
    - cython==0.29.24
    - decorator==5.0.9
    - editdistance==0.5.3
    - emoji==1.4.2
    - ftfy==6.0.3
    - future==0.18.2
    - huggingface-hub==0.0.16
    - hyperpyyaml==1.0.0
    - idna==3.2
    - isodate==0.6.0
    - jiwer==2.3.0
    - joblib==1.0.1
    - kiwisolver==1.3.2
    - librosa==0.8.1
    - llvmlite==0.37.0
    - matplotlib==3.4.3
    - munkres==1.1.4
    - noisereduce==2.0.0
    - numba==0.54.0
    - numpy==1.20.3
    - packaging==21.0
    - panphon==0.19
    - phonemizer==2.2.2
    - pillow==8.3.2
    - pooch==1.5.1
    - pycparser==2.20
    - pygments==2.10.0
    - pyloudnorm==0.1.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - python-graphviz==0.17
    - python-levenshtein==0.12.2
    - pyworld==0.3.0
    - pyyaml==5.4.1
    - regex==2021.8.28
    - requests==2.26.0
    - resampy==0.2.2
    - rfc3986==1.5.0
    - rich==9.10.0
    - ruamel-yaml==0.17.16
    - ruamel-yaml-clib==0.2.6
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - segments==2.2.0
    - sentencepiece==0.1.96
    - sounddevice==0.4.2
    - soundfile==0.10.3.post1
    - speechbrain==0.5.10
    - tabulate==0.8.9
    - threadpoolctl==2.2.0
    - torch-complex==0.2.1
    - torchviz==0.0.2
    - tqdm==4.62.2
    - typing-extensions==3.10.0.2
    - unicodecsv==0.14.1
    - unidecode==1.2.0
    - unsilence==1.0.8
    - urllib3==1.26.6
    - wcwidth==0.2.5
