name: toucan_conda_venv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cudatoolkit=11.3.1
  - freetype=2.11.0
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy-base=1.22.3
  - openssl=1.1.1q
  - pip=22.1.2
  - pydub=0.25.1
  - pypinyin=0.46.0
  - python=3.8.13
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - readline=8.1.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - torchaudio=0.10.1
  - typing_extensions=4.1.1
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - argparse==1.4.0
    - attrs==21.2.0
    - audioread==2.1.9
    - auraloss==0.2.1
    - cffi==1.14.6
    - charset-normalizer==2.0.4
    - clean-text==0.5.0
    - clldutils==3.9.0
    - colorama==0.4.4
    - colorlog==6.4.1
    - commonmark==0.9.1
    - csvw==1.11.0
    - cycler==0.10.0
    - cython==0.29.24
    - decorator==5.0.9
    - editdistance==0.5.3
    - emoji==1.4.2
    - ftfy==6.0.3
    - future==0.18.2
    - huggingface-hub==0.0.16
    - hyperpyyaml==1.0.0
    - idna==3.2
    - isodate==0.6.0
    - jiwer==2.3.0
    - joblib==1.0.1
    - kiwisolver==1.3.2
    - librosa==0.8.1
    - llvmlite==0.37.0
    - matplotlib==3.4.3
    - munkres==1.1.4
    - noisereduce==2.0.0
    - numba==0.54.0
    - numpy==1.20.0
    - packaging==21.0
    - panphon==0.19
    - phonemizer==2.2.2
    - pillow==8.3.2
    - pooch==1.5.1
    - praat-parselmouth==0.4.1
    - pycparser==2.20
    - pygments==2.10.0
    - pyloudnorm==0.1.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - python-graphviz==0.17
    - python-levenshtein==0.12.2
    - pyworld==0.3.0
    - pyyaml==5.4.1
    - regex==2021.8.28
    - requests==2.26.0
    - resampy==0.2.2
    - rfc3986==1.5.0
    - rich==9.10.0
    - ruamel-yaml==0.17.16
    - ruamel-yaml-clib==0.2.6
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - segments==2.2.0
    - sentencepiece==0.1.96
    - sounddevice==0.4.2
    - soundfile==0.10.3.post1
    - speechbrain==0.5.10
    - tabulate==0.8.9
    - threadpoolctl==2.2.0
    - torch-complex==0.2.1
    - torchviz==0.0.2
    - tqdm==4.62.2
    - typing-extensions==3.10.0.2
    - unicodecsv==0.14.1
    - unidecode==1.2.0
    - unsilence==1.0.8
    - urllib3==1.26.6
    - wcwidth==0.2.5
